"""
Sandbox Executor — Runs LLM-generated Python code in an isolated subprocess.

Security measures:
- Subprocess with timeout (default 30s)
- Import whitelist enforcement
- No network access in generated code
- Output size limits
- Temporary file isolation
"""

import subprocess
import sys
import os
import tempfile
import uuid
import json
import re
from dataclasses import dataclass, field
from typing import Optional, List
from pathlib import Path


@dataclass
class ExecutionResult:
    """Result of a sandbox code execution."""
    success: bool
    stdout: str = ""
    stderr: str = ""
    chart_paths: List[str] = field(default_factory=list)
    execution_time: float = 0.0
    code_executed: str = ""


# Allowed imports in sandbox — nothing dangerous
ALLOWED_IMPORTS = {
    "pandas", "pd",
    "numpy", "np",
    "matplotlib", "matplotlib.pyplot", "plt",
    "plotly", "plotly.express", "plotly.graph_objects", "plotly.graph_objs",
    "plotly.subplots",
    "seaborn", "sns",
    "sklearn", "sklearn.linear_model", "sklearn.model_selection",
    "sklearn.preprocessing", "sklearn.metrics", "sklearn.cluster",
    "statsmodels", "statsmodels.tsa", "statsmodels.tsa.arima",
    "statsmodels.tsa.statespace.sarimax", "statsmodels.tsa.holtwinters",
    "statsmodels.api",
    "datetime", "math", "statistics", "collections", "itertools",
    "json", "re", "io", "warnings",
}

# Blocked patterns — dangerous operations
BLOCKED_PATTERNS = [
    r"\bos\.system\b",
    r"\bsubprocess\b",
    r"\b__import__\b",
    r"\beval\b",
    r"\bexec\b",
    r"\bopen\s*\(",        # Don't allow arbitrary file opens (we handle chart saves)
    r"\bshutil\b",
    r"\brequests\b",
    r"\burllib\b",
    r"\bsocket\b",
    r"\bhttp\b",
    r"\bsys\.exit\b",
    r"\bquit\b",
    r"\bexit\b",
]


class SandboxExecutor:
    """
    Executes Python code in an isolated subprocess with security constraints.

    Usage:
        executor = SandboxExecutor()
        result = executor.execute(code_string, dataframe)
    """

    def __init__(self, timeout: int = 30, max_output_chars: int = 50000):
        self.timeout = timeout
        self.max_output_chars = max_output_chars
        self.project_root = Path(__file__).parent.parent
        self.sandbox_dir = self.project_root / "sandbox_temp"
        self.sandbox_dir.mkdir(exist_ok=True)

    def execute(self, code: str, df_path: str, timeout: Optional[int] = None) -> ExecutionResult:
        """
        Execute Python code in a subprocess sandbox.

        Parameters
        ----------
        code : str
            The Python code to execute (generated by the agent).
        df_path : str
            Path to the CSV file containing the DataFrame.
        timeout : int, optional
            Execution timeout in seconds. Defaults to self.timeout.

        Returns
        -------
        ExecutionResult
            Containing success status, stdout, stderr, and chart paths.
        """
        timeout = timeout or self.timeout

        # Security check
        security_issues = self._check_security(code)
        if security_issues:
            return ExecutionResult(
                success=False,
                stderr=f"Security violation: {'; '.join(security_issues)}",
                code_executed=code,
            )

        # Create execution ID for temp files
        exec_id = str(uuid.uuid4())[:8]
        chart_dir = self.sandbox_dir / exec_id
        chart_dir.mkdir(exist_ok=True)

        # Build the full script with preamble
        full_script = self._build_script(code, df_path, str(chart_dir))

        # Write script to temp file
        script_path = chart_dir / "script.py"
        script_path.write_text(full_script, encoding="utf-8")

        try:
            import time
            start_time = time.time()

            # Run in subprocess
            result = subprocess.run(
                [sys.executable, str(script_path)],
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=str(chart_dir),
                env=self._get_safe_env(),
            )

            elapsed = time.time() - start_time

            # Collect chart files
            chart_paths = self._collect_charts(chart_dir)

            stdout = result.stdout[:self.max_output_chars] if result.stdout else ""
            stderr = result.stderr[:self.max_output_chars] if result.stderr else ""

            return ExecutionResult(
                success=result.returncode == 0,
                stdout=stdout,
                stderr=stderr,
                chart_paths=chart_paths,
                execution_time=round(elapsed, 2),
                code_executed=code,
            )

        except subprocess.TimeoutExpired:
            return ExecutionResult(
                success=False,
                stderr=f"Execution timed out after {timeout} seconds.",
                code_executed=code,
            )
        except Exception as e:
            return ExecutionResult(
                success=False,
                stderr=f"Sandbox error: {str(e)}",
                code_executed=code,
            )

    def _build_script(self, code: str, df_path: str, chart_dir: str) -> str:
        """
        Build the complete Python script with safe preamble.

        Injects:
        - Import statements
        - DataFrame loading
        - Chart save directory
        - Matplotlib backend config
        - Warning suppression
        """
        chart_dir_escaped = chart_dir.replace("\\", "\\\\")
        df_path_escaped = df_path.replace("\\", "\\\\")

        preamble = f'''
# ── Sandbox Preamble (auto-injected) ──────────────────────
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os

# Set chart output directory
CHART_DIR = r"{chart_dir_escaped}"

# Load the dataset
df = pd.read_csv(r"{df_path_escaped}")

# Plotly support
try:
    import plotly.express as px
    import plotly.graph_objects as go
    PLOTLY_AVAILABLE = True
except ImportError:
    PLOTLY_AVAILABLE = False

# ML support
try:
    from sklearn.linear_model import LinearRegression
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import r2_score, mean_squared_error
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

try:
    import statsmodels.api as sm
    from statsmodels.tsa.arima.model import ARIMA
    STATSMODELS_AVAILABLE = True
except ImportError:
    STATSMODELS_AVAILABLE = False

# Helper: save matplotlib figure
def save_chart(fig, name="chart"):
    path = os.path.join(CHART_DIR, f"{{name}}.png")
    fig.savefig(path, dpi=150, bbox_inches="tight",
                facecolor="#0E1117", edgecolor="none")
    plt.close(fig)
    print(f"CHART_SAVED:{{path}}")

# Helper: save plotly figure
def save_plotly_chart(fig, name="chart"):
    path = os.path.join(CHART_DIR, f"{{name}}.html")
    fig.write_html(path)
    # Also save as image
    try:
        img_path = os.path.join(CHART_DIR, f"{{name}}.png")
        fig.write_image(img_path, width=1200, height=600)
        print(f"CHART_SAVED:{{img_path}}")
    except Exception:
        pass
    print(f"PLOTLY_CHART_SAVED:{{path}}")

# Helper: print insights as JSON
def report_insights(insights_dict):
    print(f"INSIGHTS_JSON:{{json.dumps(insights_dict)}}")

# ── End Preamble ──────────────────────────────────────────

'''
        return preamble + code

    def _check_security(self, code: str) -> List[str]:
        """
        Check code for security violations.

        Returns a list of violation descriptions (empty if safe).
        """
        violations = []

        for pattern in BLOCKED_PATTERNS:
            if re.search(pattern, code):
                violations.append(f"Blocked pattern detected: {pattern}")

        return violations

    def _get_safe_env(self) -> dict:
        """
        Build a restricted environment for the subprocess.
        Inherits PATH and Python paths but removes sensitive vars.
        """
        safe_env = os.environ.copy()
        # Remove potentially sensitive environment variables
        for key in ["GOOGLE_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY",
                     "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]:
            safe_env.pop(key, None)
        return safe_env

    def _collect_charts(self, chart_dir: Path) -> List[str]:
        """
        Collect paths to generated chart files from the sandbox directory.
        """
        chart_paths = []
        if chart_dir.exists():
            for ext in ["*.png", "*.jpg", "*.svg", "*.html"]:
                chart_paths.extend([str(p) for p in chart_dir.glob(ext)])
        return chart_paths

    def save_dataframe(self, df, exec_id: str = None) -> str:
        """
        Save a DataFrame to a temp CSV file for sandbox access.

        Returns the path to the saved file.
        """
        exec_id = exec_id or str(uuid.uuid4())[:8]
        temp_dir = self.sandbox_dir / exec_id
        temp_dir.mkdir(exist_ok=True)
        path = temp_dir / "input_data.csv"
        df.to_csv(path, index=False)
        return str(path)

    def cleanup(self, exec_id: str = None):
        """
        Clean up temporary sandbox files.
        If exec_id is None, cleans all temp files.
        """
        import shutil
        if exec_id:
            target = self.sandbox_dir / exec_id
            if target.exists():
                shutil.rmtree(target, ignore_errors=True)
        else:
            if self.sandbox_dir.exists():
                shutil.rmtree(self.sandbox_dir, ignore_errors=True)
                self.sandbox_dir.mkdir(exist_ok=True)
